### ISSUE TITLE
Default-enabled patches not working properly

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/PatchManager#2]
If I put the patch in ActiveMMPatches folder only, start the game and deactivate the patch, I can not re-enable it after another game-restart. To me it seems like the patch is beeing deleted instead of moved/copied. After I disable it, the MyMMPatch.cfg is not located in PluginData as it should be (not in GameData/MyMod/... nor in GameData/PatchManager/...). The PatchManager config is pointing to " MyMod/PatchManager/PluginData/MyMMPatch.cfg " as described in the OP.

One little detail: The OP is missing the " modName = NameOfMyMod " config-node.

**Comment by EleusisLaArwall** [comment]
My pull-request to Interstellar Fuel Switch is already merged and the files are located here:
https://github.com/sswelm/KSP-Interstellar-Extended/tree/master/GameData/InterstellarFuelSwitch/PatchManager
Currently I have all MMconfigs in PluginData and the (by default) active MMconfigs are also in ActiveMMPatches folder.

**Comment by linuxgurugamer** [comment]
You are missing an  option:
installedWithMod = true
which tells PatchManager that this is an initially installed patch.  
I just updated the OP with this information
