### ISSUE TITLE
Opening any category adds empty space to all of them (KSP 1.9.x, PM 0.0.17.1)

### ISSUE THREAD

**Issue by Lafreakshow** [linuxgurugamer/PatchManager#7]
When opening any of the categories, the mod seems to "open" (as in, add empty space where Items would be) for all of them, but only the items for the category that was clicked will actually be displayed. At first this led to a lot of confusion because opening some categories means all others will be shifted down by a lot, resulting in the window looking as if it was just empty.

This screenshot probably says it better than I could ever describe it (note the difference in scrollbar size).

![screenshot7](https://user-images.githubusercontent.com/1574685/89102682-e0d4e980-d40b-11ea-85a1-299765cea7b1.png)

And for reference: 

![screenshot8](https://user-images.githubusercontent.com/1574685/89102748-5c369b00-d40c-11ea-8290-9da7223a3c9e.png)

I went through the logs as well but there wasn't anything out of the ordinary there.

Aside from this the mod works as advertised in 1.9.x (as far as I can tell at least) so maybe the max version could be bumped up a bit. I remember first noticing this bug when I was still playing on my other install on 1.8.x. So it seems that the above bug isn't related to the KSP version.

**Comment by linuxgurugamer** [comment]
Thanks, good pics, I'll see if I can fix it in a few days.
Regarding max version, there is no "max" version listed.  All my mods are expected to work without any issues in 1.10, and I don't have time to update all the mod thread right now

**Comment by Lafreakshow** [comment]
Oh wow. You're right, it says 1.8 and later right there in CKAN. Somehow I only saw the 1.8, my apologies. It's understandable that you can't keep all the threads updated considering you pretty much maintain half the CKAN registry. Thanks for that by the way, Awesome job.

**Comment by linuxgurugamer** [comment]
Resolved, thank you for the report
